apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: td8gbk8f1-java-quarkus
  janus-idp.io/tekton: td8gbk8f1-java-quarkus
  backstage.io/kubernetes-id: td8gbk8f1-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: td8gbk8f1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
